version: 1
formatters:
  simple:
    format: "%(name)s (%(processName)s)(t %(thread)d: %(threadName)s) [%(levelname)s]: %(message)s"
  with_date:
    format: "%(asctime)s %(name)s (%(processName)s)(t %(thread)d: %(threadName)s) [%(levelname)s]: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout
  file:
    backupCount: 3
    class: logging.handlers.RotatingFileHandler
    filename: log/mailpy.log
    formatter: with_date
    level: DEBUG
    maxBytes: 104857600
root:
  level: DEBUG
  handlers: [console, file]
